// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdWEBNWs6n22W_akrZtZMUiHSDL8JkEZM',
    appId: '1:209468218481:web:077d1ce2464d250813cfd0',
    messagingSenderId: '209468218481',
    projectId: 'iron-radio-346208',
    authDomain: 'iron-radio-346208.firebaseapp.com',
    storageBucket: 'iron-radio-346208.appspot.com',
    measurementId: 'G-15MLQYDHK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7vy0dC-k_QyLqhfTstgL_y2dJZMAAVfo',
    appId: '1:209468218481:android:abd725479be18f1113cfd0',
    messagingSenderId: '209468218481',
    projectId: 'iron-radio-346208',
    storageBucket: 'iron-radio-346208.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeSBN9s5IYTaWFGXscnsEMZ6w0O-LQ8nY',
    appId: '1:209468218481:ios:908534546df498e813cfd0',
    messagingSenderId: '209468218481',
    projectId: 'iron-radio-346208',
    storageBucket: 'iron-radio-346208.appspot.com',
    iosClientId: '209468218481-vf5fhrqt2rc2jursm7qug1gtpdmpa79s.apps.googleusercontent.com',
    iosBundleId: 'com.example.kebapp',
  );
}
